export const Fonts = {
  Black_Italic: 'Exo Soft Black Italic',
  Black: 'Exo Soft Black',
  Bold_Italic: 'Exo Soft Bold Italic',
  Bold: 'Exo Soft Bold',
  Extra_Bold_Italic: 'Exo Soft Extra Bold Italic',
  Extra_Bold: 'Exo Soft Extra Bold',
  Extra_Light_Italic: 'Exo Soft Extra Light Italic',
  Extra_Light: 'Exo Soft Extra Light',
  Italic: 'Exo Soft Italic',
  Light_Italic: 'Exo Soft Light Italic',
  Light: 'Exo Soft Light',
  Medium_Italic: 'Exo Soft Medium Italic',
  Medium: 'Exo Soft Medium',
  Semi_Bold_Italic: 'Exo Soft Semi Bold Italic',
  Semi_Bold: 'Exo Soft Semi Bold',
  Thin_Italic: 'Exo Soft Thin Italic',
  Soft_Thin: 'Exo Soft Thin',
  Soft: 'Exo Soft',
  // Helvetical font
  HelBold: 'Helvetica Neu Bold',
  HelBlackCond: 'HelveticaNeue BlackCond.ttf',
  HelLight: 'HelveticaNeue Light',
  HelMedium: 'HelveticaNeue Medium',
  HelThin: 'HelveticaNeue Thin',
  Hel: 'HelveticaNeue',
  HelBd: 'HelveticaNeueBd',
  HelHv: 'HelveticaNeueHv',
  Hellt: 'HelveticaNeueIt',
  HelLt: 'HelveticaNeueLt',
  HelMed: 'HelveticaNeueMed',
};
